---
language: php
php: 7.4
services: docker

env:
  global:
    - CONFIG: tests/config.yml
      MAKEFILE: example.drupal.make.yml
      COMPOSERFILE: example.drupal.composer.json
      HOSTNAME: drupalvm.test
      MACHINE_NAME: drupalvm
      IP: 192.168.88.88
      DRUPALVM_DIR: /var/www/drupalvm
      DRUSH_BIN: drush
      TEST_INSTALLED_EXTRAS: true
      CONTAINER_ID: dvm-test

  matrix:
    # Defaults - Ubuntu 18.04.
    - type: defaults
      distro: ubuntu1804
    # Defaults - Debian 10.
    - type: debian
      distro: debian10
    # Defaults - CentOS 8.
    - type: centos
      distro: centos8
      local_config: tests/centos-8.config.yml

    # PHP 7.3 - Ubuntu 18.04.
    - type: defaults
      distro: ubuntu1804
      local_config: tests/ubuntu-18-php73.config.yml
      DRUSH_BIN: "${DRUPALVM_DIR}/drupal/vendor/bin/drush"
      TEST_INSTALLED_EXTRAS: false

    # PostgreSQL - Ubuntu 18.04.
    - type: postgresql
      distro: ubuntu1804
      local_config: tests/ubuntu-18-postgresql.config.yml
      DRUSH_BIN: "${DRUPALVM_DIR}/drupal/vendor/bin/drush"
      config_dir: /var/www/drupalvm/config
      TEST_INSTALLED_EXTRAS: false

before_install:
  # Install lint tools.
  - gem install rubocop

script:
  # Vagrantfile syntax check.
  - 'rubocop ./Vagrantfile ./lib/drupalvm --except Metrics/LineLength,Security/Eval,Style/MutableConstant,Metrics/BlockLength,Metrics/MethodLength,Style/ConditionalAssignment,Style/IfUnlessModifier'

  # Run tests.
  - composer run-tests
