# Generated by Django 3.2 on 2020-06-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200623_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('produit', models.ManyToManyField(related_name='_vendeur_produit_+', through='blog.Offre', to='blog.Produit')),
                ('produits_sans_prix', models.ManyToManyField(related_name='veudeur', to='blog.Produit')),
            ],
        ),
        migrations.AlterField(
            model_name='offre',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vendeur'),
        ),
        migrations.DeleteModel(
            name='Veudeur',
        ),
    ]
