# Generated by Django 3.2 on 2020-06-22 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200622_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie'),
        ),
    ]
