# Generated by Django 3.2 on 2020-06-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200623_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
