# Generated by Django 3.2 on 2020-06-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
