# Generated by Django 3.2 on 2020-06-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200623_1510'),
    ]

    operations = [
    ]
