# Generated by Django 3.2 on 2020-06-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200625_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produits_sans_prix',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='moteur',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['date'], 'verbose_name': 'article'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Categorie',
            new_name='categorie',
        ),
        migrations.DeleteModel(
            name='Moteur',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
