# Generated by Django 3.2 on 2020-07-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20200706_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniURL',
            new_name='MiniURLs',
        ),
    ]
